title: ELEC3004
intro: Digital Linear Systems: Signals & Control.
intro_bg: nasa-bg.png
author:
  name: Patrick Mahoney
  email: 'p.mahoney2@uq.edu.au'
metadata:
    description: 'ELEC3004 - Digital Linear Systems: Signals & Control Course Website'

